
GET http://localhost:5000 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDUyMDY1NjIsImV4cCI6MTYwNTIxMDE2MiwiYXVkIjoiNWZhZDdjYWUzYjJjOTc5ZjcwNzFlODQyIiwiaXNzIjoiYW1hemluZy5jb20ifQ.BbfMeCcnUF73sn06nuxvJZgYkSVKtzg15eZJUE4N1LU

### Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
   "email": "laura3@gmail.com",
   "password": "12133"
}


###  Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "email": "liu@gmail.com",
   "password": "12133"
}

###  Refresh Token Route
POST http://localhost:5000/auth/refresh-token 
Content-Type: application/json

{
   "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDUyMDY1NjIsImV4cCI6MTYzNjc2NDE2MiwiYXVkIjoiNWZhZDdjYWUzYjJjOTc5ZjcwNzFlODQyIiwiaXNzIjoiYW1hemluZy5jb20ifQ.0Wkg0mkWLDNrtUSU43V1tF8pKdx9G-3GxIZHE88OaS4"
}

### Logout Route
DELETE http://localhost:5000/auth/logout